// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL746hZ46B32ELnQoU7Z0jST8R8VpXlTo',
    appId: '1:733388935055:web:3178dadc364a1efba045fa',
    messagingSenderId: '733388935055',
    projectId: 'cutmarkethub',
    authDomain: 'cutmarkethub.firebaseapp.com',
    storageBucket: 'cutmarkethub.appspot.com',
    measurementId: 'G-6XB9HR0696',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhPR-3HJfxLfyyVvuC0PWT3yI5mDr6aVE',
    appId: '1:733388935055:android:426c761e08130f8aa045fa',
    messagingSenderId: '733388935055',
    projectId: 'cutmarkethub',
    storageBucket: 'cutmarkethub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdEj3YDC9tvLXKRK692uzmX-dkC--RkUY',
    appId: '1:733388935055:ios:64f128e4c0744ec0a045fa',
    messagingSenderId: '733388935055',
    projectId: 'cutmarkethub',
    storageBucket: 'cutmarkethub.appspot.com',
    iosClientId: '733388935055-pg9lkjd01gsbj1s008l34a4g25205hbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.cutMarketHubClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdEj3YDC9tvLXKRK692uzmX-dkC--RkUY',
    appId: '1:733388935055:ios:64f128e4c0744ec0a045fa',
    messagingSenderId: '733388935055',
    projectId: 'cutmarkethub',
    storageBucket: 'cutmarkethub.appspot.com',
    iosClientId: '733388935055-pg9lkjd01gsbj1s008l34a4g25205hbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.cutMarketHubClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL746hZ46B32ELnQoU7Z0jST8R8VpXlTo',
    appId: '1:733388935055:web:cef422e64032f9c0a045fa',
    messagingSenderId: '733388935055',
    projectId: 'cutmarkethub',
    authDomain: 'cutmarkethub.firebaseapp.com',
    storageBucket: 'cutmarkethub.appspot.com',
    measurementId: 'G-0YBFVDRGE6',
  );
}
